---
# Configuration yamllint pour le monorepo d'observabilité
extends: default

rules:
  line-length:
    max: 160
    level: warning
  document-start: disable
  comments:
    min-spaces-from-content: 1
  comments-indentation: disable
  indentation:
    spaces: 2
    indent-sequences: consistent
  truthy:
    allowed-values: ["true", "false"]
    check-keys: false
  braces:
    max-spaces-inside: 1

ignore: |
  .terraform/
  *.sops.yaml
  docs/imgs/
  node_modules/
  gui/node_modules/
  gui/.next/
  test/cloud-init/
