# Flux applicatifs autorisés (deny-by-default étant actif).
---
# ingestion -> backends (push logs/metrics/traces)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingestion-to-backends
  namespace: backends
spec:
  podSelector: {}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingestion
---
# backends -> storage (S3/MinIO)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-backends-to-storage
  namespace: storage
spec:
  podSelector: {}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: backends
---
# visualization (Grafana) -> backends (lecture datasources)
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-visualization-to-backends
  namespace: backends
spec:
  podSelector: {}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: visualization
---
# monitoring (Prometheus) -> scrape de toutes les couches
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-monitoring-scrape
  namespace: backends
spec:
  podSelector: {}
  policyTypes: [Ingress]
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
