---
# Source Helm partagée pour Loki, Mimir et Tempo.
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: backends
spec:
  interval: 1h
  type: oci
  url: oci://${HARBOR_REGISTRY}/charts
