---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mimir
  namespace: backends
spec:
  interval: 30m
  chart:
    spec:
      chart: mimir-distributed
      version: "5.4.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    mimir:
      structuredConfig:
        common:
          storage:
            backend: s3
            s3:
              endpoint: minio.storage.svc.cluster.local:9000
              bucket_name: mimir
              access_key_id: ${MINIO_ACCESS_KEY}
              secret_access_key: ${MINIO_SECRET_KEY}
              insecure: false
        limits:
          compactor_blocks_retention_period: ${MIMIR_RETENTION}
        multitenancy_enabled: true
    distributor:
      replicas: 2
    ingester:
      replicas: ${MIMIR_INGESTER_REPLICAS}
      zoneAwareReplication:
        enabled: true
    querier:
      replicas: 2
    compactor:
      replicas: 1
    store_gateway:
      replicas: 1
