---
all:
  children:
    linux_debian:
      hosts:
        stg-debian-01:
          ansible_host: 10.20.1.11
    linux_rhel:
      hosts:
        stg-rhel-01:
          ansible_host: 10.20.1.21
    windows:
      hosts:
        stg-win-01:
          ansible_host: 10.20.1.31
      vars:
        ansible_connection: winrm
        ansible_winrm_transport: ntlm
