apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - cert-manager.yaml
  - cluster-issuer-vault.yaml
  - kyverno.yaml
  - kyverno-policies/require-signed-images.yaml
  - kyverno-policies/pod-security.yaml
  - network-policies/default-deny.yaml
  - network-policies/allow-dns.yaml
  - network-policies/allow-flows.yaml
  - network-policies/allow-egress.yaml
  - rbac/observability-rbac.yaml
